cout << "Enter a number"<<endl;
    // int a;
    // cin >> a;
    // cout << "Entered number is "<<a<<endl; 
    // cout << sizeof(a)<<endl;
    // char ch='a';
    // cout << "Entered character is "<<ch<<endl; 
    // double d=5.7;
    // int x=(int)d;
    // cout<<"value of double x "<<x<<endl;